services:
  booking_app_service:
    container_name: "booking_app"
    build:
      context: .
    ports:
      - "8888:8000"
    networks:
      - booking_network
    env_file:
      - .env

  booking_celery_worker_service:
    container_name: "booking_celery_worker"
    build:
      context: .
    networks:
      - booking_network
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"


  booking_celery_beat_service:
    container_name: "booking_celery_beat"
    build:
      context: .
    networks:
      - booking_network
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"

networks:
  booking_network:
    external: true